# Generated by Django 4.2.2 on 2023-06-30 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todolist',
            name='detailed_description',
            field=models.TextField(default='', verbose_name='Подробное описание'),
        ),
    ]
